name: Reserva automática AimHarder

on:
  schedule:
    - cron: '0 18 * * *' 
  workflow_dispatch:  # Permite ejecución manual

jobs:

  reserva:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Construir y ejecutar el contenedor
        run: |
          docker build -t aimharder-bot .
          docker run --rm aimharder-bot

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  

